### PR TITLE
Add shorthand function to merge two pre-existing RTStruct structure sets

### PR DESCRIPTION
**Pull request by rheg49**
- Merge two structure sets belonging to same image series to one resulting structure set 
- Check DICOM metadata for compatibility with one another and with image series 
- Append `ROIContourSequence`, `StructureSetROISequence` and `RTROIObservationsSequence` of first dataset to array of second dataset and save merged dataset as new RTStruct file afterwards 
- Edit ROI reference number to avoid ambiguity, check datasets for name duplication

### CODE REVIEW

**Comment by rheg49** [comment]
Had to merge two RTStructs (one for OARs, one for targets) and stumbled across your repository. First solution with the already existing functions was to create masks from one existing dataset and then re-add the mask to the second dataset. But with that solution the other metadata such as the color of the ROI got lost, so I coded my own version keeping all metadata and just working on the level of the data resulting from `dcmread`. Maybe this could be interesting for your toolbox?

**Comment by asim-shrestha** [comment]
Hey Robin! Thanks for looking into this :) 

I think this is a great addition to the library but will need some modifications before we're able to bring it in. A few notes:
- We should use the underlying RTStruct type within this package itself for all of the merging operations. This ensures we can avoid a hard dependency on pydicom in multiple places. I understand that this results in some metadata loss. Is there any other metadata you're looking for besides color? We should work to include that in `add_roi` itself first. And small note, color is already an optional parameter for add_roi, did it not work for your use case?
- The merge function shouldn't care about persistence of the rt struct so we can remove the code to write it to the filesystem
- We should place this within a separate merging class

**Comment by awtkns** [comment]
It would probably be also good to add some documentation in the readme so people know that this exists.

**Comment by asim-shrestha** [comment]
Thanks for making those changes @rheg49! I think this is a fair middle ground solution. If you can, would you mind submitting a ticket to this repo with all of the information that would be missing from a call to add_roi? We should support adding those values within the tool.

In terms of tests, I was referring to the unit tests we have for the project found https://github.com/qurit/rt-utils/tree/main/tests. Maybe a few tests demonstrating the following merge cases:
- Merging two rt structs with no ROIs
- Merging two rt structs where rt struct 1 has an ROI but the other doesn't and vice versa
- Merging two rt structs, each having multiple ROIs with no conflicts
- Merging two rt structs, each having multiple ROIs with some conflicts
I've created a separate ticket for tests: https://github.com/qurit/rt-utils/issues/72
Feel free to tackle it if you'd like :)

**Comment by rheg49** [comment]
Thanks for merging my code into your project! I recently submitted an issue on the DICOM tag missing in the `add_roi` call. I also added a MWE for the RTStructMerger to the README.md.
For the tests I currently have no idea how to implement so I think I will need more time to get used to the coding structure to adapt the tests to the use case of RTStructMerger.

**Pull request merged**
